### ISSUE TITLE
Mean of p-values in aldex.kw()

### ISSUE THREAD

**Issue by masgra** [ggloor/ALDEx_bioc#12]
Hi,
this is more of an theoretical issue. I see that p-values, after calculating them MC-instance wise, get averaged per feature. However, I would guess that using the median p-value should be preferable, since the distribution of those p-values is limited to an interval of [0 1], not guaranteed to be Gaussian, and not sampled sufficiently deep enough to eliminate the effect of "outliers", generated by chance. What are your thoughts about it?

Cheers
Martin

**Comment by ggloor** [comment]
We mainly use means because they are faster to calculate (rowMeans function) than medians and the p value test function is pretty slow anyway. The initial development used thousands of Monte-Carlo replicates and outliers were not much of a problem, but now we often use dozens of replicates for efficiency. The idea of using medians is worth trying to see if it makes much of a difference. I can test that to see how it behaves.

In my hands, the mean function is not much affected by outliers since the mean p-value returned is (relatively) stable when I run the same dataset multiple times. The only features that are affected are edge cases (near the cutoff chosen).
