### ISSUE TITLE
Value reported by aldex.corr

### ISSUE THREAD

**Issue by valscherz** [ggloor/ALDEx_bioc#16]
We have observed in the [in the aldex.corr code,](https://github.com/ggloor/ALDEx_bioc/blob/45209d27ff2fb22239cbb0140993a10c329dccc1/R/clr_corr-tpq.R) that the test statistic value ("statistic") from cor.test is being recovered and assigned to "r" while from the description in the manual I would expect here the correlation value ("estimate").
Is it an error or is it here something I am missing ?

Best regards

Valentin

**Comment by randridge** [comment]
I noticed the same thing. The function on Bioconductor has this issue but in your development code you have a much richer function (that does both Pearson and Spearman correlations, and returns E(rho), p-value, and FDR-corrected p-value for both). Is there a plan to put this fuller version of the function on Bioconductor?

BTW - thanks for a really useful package with good documentation that has been easy to follow-along with and learn from!
-Rebecca

**Comment by ggloor** [comment]
this is now fixed in the development version, and I will push it to the release version as well. 

By the way, you have access to the full set of options in the corr.test function as well. the only thing that changed was the way it was described. For example, to use kendall's tau with continuity correction:

corr.test2 <- aldex.corr(x, cont.var, method="kendall", continuity=T)
