### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by stro0070** [ggloor/ALDEx_bioc#9]
Hi,

Can ALDEx2 be expanded to do post-hoc testing and report results of comparisons between multiple groups, like it does between two groups? For example, my project has 16 different treatments, and I would like to be able to see whether features (OTUs) are significantly more abundant in certain treatments over others, identified by a Tukey's HSD significance category letter or something similar. It would also be great to be able to extract mean CLRs from each treatment as well as CLRs associated with features (OTUs) from individual samples.

Thanks,
Noah Strom

**Comment by 145218415** [comment]
Hi, 

I have the same question, there is any advance conserning this functionnality ? 

In my case I got simple experimental design : 4 different treatments and only 1 timepoint at the end of the experiment, so I thought I should use `aldex.kw()`, and then apply a post-hoc test allowing comparison between treatments. 

If I understood well, in order to be able to compare abundances between 2 groups, I have to use instead `aldex.glm()` with a formula like that :  `mm <- model.matrix(~ treatment + Mouse.ID , covariates)`  ?
 
Thank you in advance ! 
Thibault

**Comment by ggloor** [comment]
I have not yet included post-hoc tests, but I agree it is urgent to do so.
And yes, the aldex.glm function is what you should use.

**Comment by trichterhb** [comment]
Hi,
maybe a bit late to the party, but what is the status of the post-hoc? It would be extremely valuable to have.
